name: Build and Deploy Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout Doxygen Awesome
        uses: Mushus/checkout-submodule@v1.0.1
        with:
          submodulePath: ./docs/doxygen-awesome-css
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: "docs/Doxyfile"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs-output/html # The folder the action should deploy.
